[build]
  publish = "."
  functions = "netlify/functions"

# Prefer fast 301 redirects so crawlers fetch OG directly from the origin
[[redirects]]
  from = "/posts/*"
  to = "https://todayonus.com/posts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/posts"
  to = "https://google.com"
  status = 301
  force = true

# Optional: keep other paths served normally (or add your own rules)
