[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/posts/*"
  to = "/.netlify/functions/simple-render"
  status = 200

[[redirects]]
  from = "/posts"
  to = "/.netlify/functions/simple-render"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/simple-render"
  status = 200