[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/posts/*"
  to = "/.netlify/functions/test-simple"
  status = 200

[[redirects]]
  from = "/posts"
  to = "/.netlify/functions/test-simple"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
