[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/posts/*"
  to = "/.netlify/functions/render-page"
  status = 200

[[redirects]]
  from = "/posts"
  to = "/.netlify/functions/render-page"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render-page"
  status = 200
